image: golang:1.10.0

variables:
  GO_PROJECT: github.com/moogar0880/venom

stages:
  - test

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - go get -u github.com/golang/dep/cmd/dep
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
  - cd ${GOPATH}/src/${GO_PROJECT}

test-project:
  stage: test
  script:
    - make -e vendor test
